Repository HathorNetwork/hathor-wallet-headless, pull requests merged in 2022-03, with the labels that each got.

#152 Integration tests: simple send-tx, send-tx, create-tokens, mint and melt tokens
  .gitignore
  __tests__/integration/address-info.test.js
  __tests__/integration/balance.test.js
  __tests__/integration/configuration/config.js.template
  __tests__/integration/configuration/test.config.js
  __tests__/integration/create-token.test.js
  __tests__/integration/docker-compose.yml
  __tests__/integration/melt-tokens.test.js
  __tests__/integration/mint-tokens.test.js
  __tests__/integration/send-tx.test.js
  __tests__/integration/simple-send-tx.test.js
  __tests__/integration/transaction.test.js
  __tests__/integration/tx-history.test.js
  __tests__/integration/txLogger.js
  __tests__/integration/utils/test-utils-integration.js
  __tests__/integration/utils/wallet-helper.js
  jest-integration.config.js
  setupTests-integration.js
Labels: tests

#160 Fix issue when user filters UTXOs by address query and custom tokens
  __tests__/__fixtures__/http-fixtures.js
  __tests__/address.test.js
  __tests__/addresses.test.js
  __tests__/balance.test.js
  __tests__/integration/send-tx.test.js
  __tests__/integration/utils/wallet-helper.js
  __tests__/send-tx.test.js
  __tests__/test-utils.js
  __tests__/tx-history.test.js
  __tests__/utxo.test.js
  src/index.js
Labels: bug

#165 chore: upgrade wallet lib v0.33.1
  package-lock.json
  package.json
Labels: dependencies
