Repository HathorNetwork/hathor-wallet-headless, pull requests merged in 2022-04, with the labels that each got.

#156 feat: Multisig Support
  .github/workflows/integration-test.yml
  .gitignore
  MULTISIG.md
  README.md
  __tests__/__fixtures__/config-fixture.js
  __tests__/__fixtures__/feature-fixture.js
  __tests__/__fixtures__/http-fixtures.js
  __tests__/create-tx-proposal.test.js
  __tests__/decode.test.js
  __tests__/features.test.js
  __tests__/get-my-signatures.test.js
  __tests__/integration/configuration/config-fixture.js
  __tests__/integration/configuration/config.js.template
  __tests__/integration/multisig.test.js
  __tests__/integration/txLogger.js
  __tests__/integration/utils/test-utils-integration.js
  __tests__/integration/utils/wallet-helper.js
  __tests__/multisig-pubkey.test.js
  __tests__/send-tx.test.js
  __tests__/start.test.js
  __tests__/test-utils.js
  __tests__/tx-proposal-sign-and-push.test.js
  __tests__/tx-proposal-sign.test.js
  config.js.docker
  config.js.template
  setupTests-integration.js
  setupTests.js
  src/api-docs.js
  src/constants.js
  src/index.js
Labels: enhancement

#164 Integration tests: utxo-filter, utxo-consolidation, create-nft
  .github/workflows/integration-test.yml
  QA.md
  __tests__/integration/address-info.test.js
  __tests__/integration/balance.test.js
  __tests__/integration/configuration/config-fixture.js
  __tests__/integration/configuration/test.config.js
  __tests__/integration/create-nft.test.js
  __tests__/integration/docker-compose.yml
  __tests__/integration/multisig.test.js
  __tests__/integration/send-tx.test.js
  __tests__/integration/tx-history.test.js
  __tests__/integration/txLogger.js
  __tests__/integration/utils/test-utils-integration.js
  __tests__/integration/utils/wallet-helper.js
  __tests__/integration/utxo-consolidation.test.js
  __tests__/integration/utxo-filter.test.js
  jest-integration.config.js
Labels: tests

#181 fix: utxo-filter parameter only-available
  __tests__/integration/utxo-filter.test.js
  src/routes/wallet/wallet.routes.js
Labels: bug
